data:
  batch_size: 200
  datafiles:
    test: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/data/mols_ir_test.pickle
    train: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/data/mols_ir_train.pickle
    val: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/data/mols_ir_eval.pickle
  max_charge: null
  normalization: minmax
  num_species: null
  num_workers: 20
  qm9_broad_ir_path: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/data/mols_ir.pkl
  seq_len: 100
  shuffle: true
  splits:
  - 0.7
  - 0.1
  - 0.2
  vocab_path: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/data/vibench_vocab.pkl
molecule_decoder:
  hidden_size: 512
  in_size: 512
  latent_size: 512
  n_heads: 4
  n_layers: 3
molecule_encoder:
  attention: 1
  coords_weight: 1.0
  device: cuda
  hidden_nf: 256
  in_edge_nf: 0
  in_node_nf: 30
  n_layers: 5
  node_attr: 1
  output_size: 512
spectra_encoder:
  d_ff: 1024
  dropout: 0.1
  dropout_emb: 0.1
  h_dim: 512
  max_time_steps: 1000
  num_heads: 7
  num_layers: 5
  output_size: 512
  patch_size: 7
  use_clf_token: true
train:
  checkpoint_dir: checkpoints/mols_ir
  device: cuda
  lr: 0.0001
  num_epochs: 500
  temperature: 1
  threshold: 0.9999
  weight_decay: 1.0e-06
  loss_type: default
wandb:
  dir: /fs-computility/ai4chem/luxinyu.p/Spectra2Structure/wandb/
  job_type: sample
  project_name: SMEN_Mols_IR
  run_name: RUN_best_config
